// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rprbcrcuthtzbopcpmlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcmJjcmN1dGh0emJvcGNwbWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODI5ODYsImV4cCI6MjA2MzA1ODk4Nn0.1XBhuzCAKWrkyyKQ4LBliugHPnpsgqbUQhL9FD32rx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);